version: "3"
services:
  db:
    image: "postgres"
    container_name: "rex-postgres"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DATABASE}
    ports:
      - "${PORT}:5432"
    # Set a volume - database is not lost after shutting down the container.
    volumes:
      - ./postgres-data:/var/lib/postgresql/